# Starter pipeline
- task: AzurePowerShell@5
  inputs:
    azureSubscription: 'Azure subscription 1 (e5f578af-b5e3-4010-b5fb-feaeae59a917)'
    ScriptType: 'FilePath'
    ScriptPath: '~/AzureAD-Powershell-Assignment1.ps1'
    errorActionPreference: 'silentlyContinue'
    azurePowerShellVersion: 'LatestVersion'
    workingDirectory: '~/'
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
